version: '3'
services:
  metabase:
    restart: always
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
      - /etc/localtime:/etc/localtime:ro